# Site settings
title: "Tin Tun Naing - Resume"
description: "Tin Tun Naing - Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tin Tun Naing"
resume_title:                   "Junior Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tinnaing347@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "New York, NY"

resume_header_contact_info:     "New York, NY • tinnaing347@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>As a mathematician by education and a software developer by trade, I have applied my problem-solving and mathematical skills and passion for sustainability and environmental issues towards building energy modeling at the City University of New York.</p>
                      <p>I enjoy developing scalable and unit-testable libraries and web APIs using microservice architecture. I have taught myself Python, R, and JavaScript. As of right now,
                      I have been working on a to-do web app with a social networking aspect.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/tinnaing347"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/tintunnaing"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts


exclude: ['vendor']
